title: Main Street Pulse
description: Main Street Pulse helps you keep track of all your business entities and properties in one convenient place. You can easily monitor your businesses, track your real estate holdings, and stay on top of important dates and milestones.
url: http://mainstreetpulse.com

permalink: /articles/:title/

collections:
  support:
    output: true
    permalink: /support/:slug
  testimonials:
    output: true
    permalink: /testimonials/:slug